version: '3'
networks:
  groceryshop:
    driver: bridge
volumes:
  db:
    driver:
      local
services:
  auth:
    container_name: auth
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - ${SERVER_PORT}:3000
    env_file:
      - .env
    networks:
      - groceryshop
    depends_on:
      - redis
      - authdb

  redis:
    container_name: redis
    image: redis:5
    networks:
      - groceryshop
  authdb:
    image: mysql:5.7
    container_name: authdb
    networks:
      - groceryshop
    ports:
      - "3307:3306"
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
      - "db:/var/lib/mysql"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}