version: "3"
networks:
  groceryshop:
    external: true
volumes:
  db:
    driver: local

  notificationdb:
    driver: local

services:
  auth:
    container_name: auth
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      domain: ${DOMAIN}
    volumes:
      - ./:/app
    ports:
      - ${SERVER_PORT}:3000
    env_file:
      - .env
    networks:
      - groceryshop
    depends_on:
      - redis
      - authdb

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - groceryshop
    volumes:
      - "./data/redis:/data"

  authdb:
    image: mysql:5.7
    container_name: authdb
    networks:
      - groceryshop
    ports:
      - "3307:3306"
    volumes:
      - "./data/auth:/docker-entrypoint-initdb.d"
      - "db:/var/lib/mysql"
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password  --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
#  notification:
#    container_name: notification
#    image: 575598310632.dkr.ecr.us-east-1.amazonaws.com/notification
#    environment:
#      domain: ${DOMAIN}
#    restart: always
#    ports:
#      - 9001:3000
#    env_file:
#      - .env
#    networks:
#      - groceryshop
#    external_links:
#      - auth
#      - notificationdb
#    depends_on:
#      - notificationdb
#
#  notificationdb:
#    image: mysql:5.7
#    container_name: notificationdb
#    networks:
#      - groceryshop
#    ports:
#      - "3309:3306"
#    volumes:
#      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
#      - "notificationdb:/var/lib/mysql"
#    restart: unless-stopped
#    command: --default-authentication-plugin=mysql_native_password
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_USER: ${DB_USERNAME}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: notification

